name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend # Change this if your frontend folder is named differently

      - name: Build Project
        run: npm run build
        working-directory: ./frontend # Change this if your frontend folder is named differently

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./frontend # Change this if your frontend folder is named differently
